#!/bin/sh
#
# @name Elikos Hexarotor x geometry
#
# @type Hexarotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
#
# @output AUX1 servo 0
# @output AUX2 servo 1
# @output AUX3 servo 2
# @output AUX4 servo 3
#
# @maintainer Elikos <info@elikos.ca>
#

set VEHICLE_TYPE mc

if [ $AUTOCNF == yes ]
then
	param set NAV_ACC_RAD 2.0
	param set RTL_RETURN_ALT 30.0
	param set RTL_DESCEND_ALT 10.0
	param set PWM_MIN 1075
	param set PWM_MAX 1950
	param set PWM_RATE 400

	param set RTL_LAND_DELAY 0
fi

# This is the servo mixer
set MIXER_AUX servo
set PWM_AUX_RATE 50
set PWM_AUX_OUT 123456


set MIXER hexa_x
# Need to set all 8 channels
set PWM_OUT 12345678